#pragma once

#define WIFI_SSID "INFINITUME9DD"
#define WIFI_PASS "TUPXh9EXQC"

#define DR_SIMI_RX_IP "192.168.1.66"
#define DR_SIMI_RX_PORT 3333

#define UDP_PAYLOAD "PING"
#define UDP_BLAST_INTERVAL_MS 20
#define UDP_PACKETS_PER_SECOND (1000 / UDP_BLAST_INTERVAL_MS)

#define WIFI_MAXIMUM_RETRY 10
#define DISPLAY_BRIGHTNESS_PERCENT 35
